### ISSUE TITLE
Single Occurrence With Multiple Times For a Day

### ISSUE THREAD

**Issue by swalke16** [seejohnrun/ice_cube#101]
I found this question on [StackOverflow ](http://stackoverflow.com/questions/7374715/ruby-ice-cube-exclude-whole-day-for-hourly-recurring-event) that shows how you can have multiple occurrences of a schedule on a single day using the hour_of_day and minute_of_hour methods on a rule.

This works great for weekly, and daily recurrences, but I couldn't seem to find a way to make a non repeating schedule that occurs multiple times in a day. For example I want a schedule that looks like:

5 am
6 am
5pm
On October 15th

I tried using daily and hourly rules with a 0 interval but this just throws a division by zero error on getting occurrences.

**Comment by martinstreicher** [comment]
I used this solution today, albeit with `.count(1)` rather than `until`.
