### ISSUE TITLE
Find occurrences whose duration intersects a time window

### ISSUE THREAD

**Issue by avit** [seejohnrun/ice_cube#154]
We have `occurrences_between`, but this only covers start times in the range, not all occurrences whose duration intersects the window (those that already started before, and are presently counted by `occurring_between?`).

I vote for adding `open_occurrences_between(t0, t1)` to cover the question from #153.

Or is there a better name for this?

```
occurrences_with_duration_between
occurrences_occurring_between
occurrences_intersecting_between
?
```

**Comment by Chosko** [comment]
what about `occurrences_intersecting(t0, t1)` ?

**Comment by jopotts** [comment]
There's a [pull request](https://github.com/seejohnrun/ice_cube/pull/302) with this working already that simply opts for a new `spans` parameter on the `enumerate_occurrences` method.

@avit It would be good to get this merged into the master branch. It's in production and working well. Thanks.

**Comment by Chosko** [comment]
+1

**Comment by avit** [comment]
Merged, closing this. Thanks all!
