### ISSUE TITLE
Deprecation warning cannot be silenced

### ISSUE THREAD

**Issue by m5rk** [seejohnrun/ice_cube#247]
Normal use of IceCube leads to annoying deprecation warning with no apparent remedy:

``` ruby
> schedule = IceCube::Schedule.new(Time.now)
=> #<IceCube::Schedule:0x007fc546c83aa8 @start_time=2014-07-31 13:13:12 -0500, @all_recurrence_rules=[], @all_exception_rules=[]>
> yaml = schedule.to_yaml
=> "---\n:start_time: &1 2014-07-31 13:13:12.818231000 -05:00\n:start_date: *1\n:rrules: []\n:rtimes: []\n:extimes: []\n"
> IceCube::Schedule.from_yaml(yaml)
IceCube: :start_date is deprecated, please use :start_time at: /Users/markmceahern/.gem/ruby/2.1.1/gems/ice_cube-0.12.1/lib/ice_cube/parsers/hash_parser.rb:11:in `to_schedule'
=> #<IceCube::Schedule:0x007fc5417ae488 @start_time=2014-07-31 13:13:12 -0500, @all_recurrence_rules=[], @all_exception_rules=[]>
```

**Comment by martinstreicher** [comment]
Does `IceCube.compatibility = 12` disable features? I am getting the spurious deprecation message as well, but I don't want to disable features I am dependent on.

**Comment by martinstreicher** [comment]
Looks ok in the source.

**Comment by lizlove** [comment]
I'm having the same error in the ice_cube-0.13.0. Is this issue still persisting? Does this fix work for later versions of IceCube?

**Comment by lizlove** [comment]
Followed @m5rk suggestion and added an initializer with ```IceCube.compatibility = 12 ``` and it fixed the error. Thanks!
