### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by avit** [seejohnrun/ice_cube#260]
Confirmed & investigating, discovered in:

https://github.com/tobiassvn/sidetiq/issues/47

**Comment by sahin** [comment]
@avit any updates on this issue?

**Comment by avit** [comment]
@sahin I haven't been able to reproduce or isolate it reliably. It might be dependent on a particular version of ruby interpreter or an interaction with threads... I'm keeping this ticket open if anyone who has seen it first-hand wants to provide some insight.

**Comment by avit** [comment]
Re-reading the linked sidetiq ticket, it seems this is only happening in ruby 1.9. We should probably close this unless something else indicates otherwise.
