### ISSUE TITLE
Still get deprecated warnings despite setting IceCube.compatibility = 12

### ISSUE THREAD

**Issue by CreativelyCloudy** [seejohnrun/ice_cube#263]
Hi,

I've read through all of the related issues and was hopeful that adding this setting to config/initializers/ice_cube.rb would help, but in my case it didn't.

The warning in the log is:
ruby-2.1.3/gems/ice_cube-0.12.1/lib/ice_cube/parsers/hash_parser.rb:11:in `to_schedule'

We're using Ruby 2.1.3, Rails 4.1.6 and ice_cube 0.12.1 and not referencing start_date anywhere in our code.

I'd love to rid the log of the extra 'noise' any ideas/help would be much appreciated.

Jeff.

**Comment by avit** [comment]
I can't reproduce your error or warning here (just cleaned up your console output so it's executable):

```ruby
require 'active_support/time'
serialized_hash = {
    :start_time => {
        :time => Time.parse("2014-10-01 17:00:00 UTC"),
        :zone => "Eastern Time (US & Canada)"
    },
        :rrules => [
          {
            :validations => {
                :day => [
                    6
                ]
            },
              :rule_type => "IceCube::WeeklyRule",
               :interval => 1,
             :week_start => 0,
                  :until => Time.parse("2014-10-04 13:00:00 -0400")
        }
    ],
        :rtimes => [],
       :extimes => [
        {
            :time => Time.parse("2014-10-04 17:00:00 UTC"),
            :zone => "Eastern Time (US & Canada)"
        }
    ]
}

IceCube::Schedule.from_hash(serialized_hash)
```

It's possible you have an older serialized schedule stored with "start_date" instead of "start_time" as a hash key. See [UPGRADING][1] for info.

[1]: https://github.com/seejohnrun/ice_cube/blob/master/UPGRADING.md
