### ISSUE TITLE
When adding schedule to an record

### ISSUE THREAD

**Issue by loed-idzinga** [seejohnrun/ice_cube#268]
Hi there, 

I'm using IceCube to add schedules to an record. When adding an record like so: 
```ruby
t.schedule = IceCube::Schedule.new(Time.now, end_time: Time.zone.now + 1.hour)
```

I get the following error:

```ruby
IceCube: :start_date is deprecated, please use :start_time at: /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/ice_cube-0.12.1/lib/ice_cube/parsers/hash_parser.rb:11:in `to_schedule'
```

But when i'm doing it the 'right' way,  (with start_time - in the docs), like so: 
```ruby
t.schedule = IceCube::Schedule.new(start_time: Time.now, end_time: Time.zone.now + 1.hour)
```

I'm getting the error, and will not save this schedule: 
```ruby
NoMethodError: undefined method `utc?' for #<Hash:0x007fdf05392470>
```
Converting the Time.zone to UTC doesn't fix this problem .. 

Also the end_time (t.schedule.end_time) is always returning null, but I guess that I'm not saving the schedule properly and that the problem above is the actual problem.

**Comment by avit** [comment]
This warning has to do with serialization to/from the database, not initializing a new schedule.

Please see [UPGRADING][1]. We'll clean this up in the next release...

[1]: https://github.com/seejohnrun/ice_cube/blob/master/UPGRADING.md

**Comment by havran** [comment]
Try GEM https://github.com/seejohnrun/ice_cube...
