### ISSUE TITLE
Allow strings to be passed in for day names

### ISSUE THREAD

**Issue by gkop** [seejohnrun/ice_cube#270]
This is to support a use case in which, for example, a rails form has checkboxes that correspond to the days of the week.

Developers might be tempted to call

```ruby
params[:days_of_week].map { |day_of_week|
  IceCube::Rule.weekly.day(day_of_week.to_sym)
}
```

which is bad because it is a symbol table overflow vulnerability.

It seems that IceCube could help us out here by forgiving our strings.

**Comment by avit** [comment]
I'm tempted to say that kind of input validation should happen elsewhere. IceCube already accepts numbers or symbols. If we allow strings too then the next thing will be "SUN" vs. "Sunday" or i18n... I think it's better if we don't try to be too smart with people's various inputs here.
