### ISSUE TITLE
How to Specify Week Start?

### ISSUE THREAD

**Issue by naomiaro** [seejohnrun/ice_cube#271]
Hi, it seems I should be able to pass a second argument here for week_start? I get an arguments error though if I try that. Is there any documentation for working with week start?

Rule.monthly(2, 1).day_of_week(1 => [1], 2 => [-1])

**Comment by avit** [comment]
You should not need a week start for monthly rules. It's only available for weekly rules, here's the original ticket: #74, I don't remember all the details.

Can you specify what you're trying to solve?

**Comment by avit** [comment]
#279 seems related... there seems to be a case for adding that week_start option for monthly rules too.
