### ISSUE TITLE
Rspec version and Test Errors

### ISSUE THREAD

**Issue by balasankarc** [seejohnrun/ice_cube#275]
Is it possible to bump Rspec dependency to the latest version? I am currently packaging ice_cube for debian and while running the tests, I got this error

IceCube::TimeUtil
  in America/Anchorage
    should be able to calculate end of dates without active_support (PENDING: around hook at ./spec/spec_helper.rb:24 did not execute the example)
    should be able to calculate beginning of dates without active_support (PENDING: around hook at ./spec/spec_helper.rb:24 did not execute the example)
    should serialize to hash without error (PENDING: around hook at ./spec/spec_helper.rb:24 did not execute the example)
  in Europe/London
    should be able to calculate end of dates without active_support (PENDING: around hook at ./spec/spec_helper.rb:24 did not execute the example)
    should be able to calculate beginning of dates without active_support (PENDING: around hook at ./spec/spec_helper.rb:24 did not execute the example)
    should serialize to hash without error (PENDING: around hook at ./spec/spec_helper.rb:24 did not execute the example)
  in Pacific/Auckland
    should be able to calculate end of dates without active_support (PENDING: around hook at ./spec/spec_helper.rb:24 did not execute the example)
    should be able to calculate beginning of dates without active_support (PENDING: around hook at ./spec/spec_helper.rb:24 did not execute the example)
    should serialize to hash without error (PENDING: around hook at ./spec/spec_helper.rb:24 did not execute the example)

IceCube::Schedule using ActiveSupport

  An error occurred in an `around(:example)` hook
    NoMethodError: undefined method `reset_all' for nil:NilClass
    occurred at /usr/lib/ruby/vendor_ruby/rspec/mocks.rb:22:in`teardown'

  works with a single recurrence time starting from a TimeWithZone (FAILED - 1)

  An error occurred in an `around(:example)` hook
    NoMethodError: undefined method `reset_all' for nil:NilClass
    occurred at /usr/lib/ruby/vendor_ruby/rspec/mocks.rb:22:in`teardown'

  works with a monthly recurrence rule starting from a TimeWithZone (FAILED - 2)

Any idea how to fix this

**Comment by avit** [comment]
RSpec should only be a development dependency, and not needed for packaging, but we'll try to get it updated for RSpec 3 anyway.

**Comment by avit** [comment]
RSpec was updated. Closing!
