### ISSUE TITLE
ice_cube not selecting the last day of the year correctly?

### ISSUE THREAD

**Issue by scriptmonkey** [seejohnrun/ice_cube#277]
I was testing with this gem and noticed when I used:
# every fourth year on new year's eve

schedule.add_recurrence_rule Rule.yearly(4).day_of_year(-1)

the date returned was 12/30 and not 12/31.

my example:
[1] pry(main)> require 'ice_cube'
=> true
[2] pry(main)> last_day_of_year = IceCube::Schedule.new(now = Time.now) do |s|
[2] pry(main)\*   s.add_recurrence_rule(IceCube::Rule.yearly.day_of_year(-1))  
[2] pry(main)\* end
=> #<IceCube::Schedule:0x00000002784590
 @all_exception_rules=[],
 @all_recurrence_rules=
  [#<IceCube::YearlyRule:0x000000023746f8
    @interval=1,
    @uses=0,
....
[3] pry(main)> last_day_of_year.next_occurrence
=> 2015-12-30 13:54:49 -0600

In order to get the 31st, I used:
   s.add_recurrence_rule(IceCube::Rule.yearly.day_of_year(0))

Am I doing something wrong?
Thank you!

**Comment by avit** [comment]
Thanks for this, I will look into it.

**Comment by Calamari** [comment]
When is #326 going in?
