### ISSUE TITLE
Is it possible to link a Schedule to a Model for querying?

### ISSUE THREAD

**Issue by chrismahon** [seejohnrun/ice_cube#278]
Hi Guys, I've got an Event model that has a :schedule column to store my recurring rules for Ice Cube, like so:

```
---
:start_time: &1 2015-01-26 00:00:00.000000000 +00:00
:start_date: *1
:rrules:
- :validations:
    :day_of_month:
    - 1
  :rule_type: IceCube::MonthlyRule
  :interval: 1
:rtimes: []
:extimes: []
```

In that example I have an Event that recurs every month but I have another Event that recurs weekly. Is there a way I can list all of the occurrences for both of these Events using ice_cube?

The aim is to list all occurrences of Events happening for any particular month like this:

**January 2015**
* Monthly Event
* Weekly Event
* Weekly Event
* Weekly Event
* Weekly Event

**February 2015**
* Monthly Event
* Weekly Event
* Weekly Event
* Weekly Event
* Weekly Event

Ideally I'd like to be able to do something like this to return all occurrences:

```
@all_events = Event.occurs_between?(now, now + 1.month)
```

Is this at all possible with ice_cube?

Thanks,
Chris

**Comment by avit** [comment]
Not possible directly.

What I've done before is just use the schedule to generate "Occurrence" entries that can be joined against with a database index. See also #175.
