### ISSUE TITLE
Depend on ActiveSupport?

### ISSUE THREAD

**Issue by dnrce** [seejohnrun/ice_cube#280]
What's the reason ice_cube tries to avoid depending on ActiveSupport? It seems like a lot of ice_cube code replicates functionality that would be a gimme if ActiveSupport were made a dependency.

**Comment by avit** [comment]
ActiveSupport is a pretty big dependency for the few core functions we could use from it. It also doesn't support anything we'd need to support plain ruby Time (it's built around its own ActiveSupport::TimeWithZone).

IceCube::TimeUtil is pretty small, and I don't see much overlap there with ActiveSupport.

While I like to use ActiveSupport in my applications, I prefer to avoid it in libraries.
