### ISSUE TITLE
Serialize as UTC always & deserialize in local time zone

### ISSUE THREAD

**Issue by morganick** [seejohnrun/ice_cube#283]
Our users specify which time zone they want all of there dates/times to appear in the UI. Therefore, we need to store everything as UTC, which is handled by Rails. However when serializing the schedule into the DB, we want to keep those times as UTC. If we store ```start_time``` as UTC then ```TimeUtil``` does all of its calculations based on UTC and not the user's time zone.

To use the code as it stands now, we would have to serialize the ```start_time``` with the user's current time zone so that ```TimeUtil``` does the right thing. However, as soon as the user changes their time zone the serialized data is now wrong.

We used the following monkey patch to get the effect that we wanted:

```
module IceCube
  module TimeUtil

    def self.serialize_time(time)
      time.utc
    end

    def self.deserialize_time(value)
      case value
      when Hash
        hash = FlexibleHash.new(value)
        hash[:time].in_time_zone
      else
        if value.respond_to? :in_time_zone
          value.in_time_zone
        elsif value.respond_to? :to_s
          Time.zone.parse(value)
        end
      end
    end
  end
end
```

**Comment by avit** [comment]
Maybe I'm misunderstanding what this is for... is this related to #282?

Schedules are already serialized with the time zone preserved when you create your schedule using a time zone. It stores the UTC timestamp, plus the original time zone annotation.

This would lose the original time zone context when serializing the schedule:

    def self.serialize_time(time)
      time.utc
    end

Are you trying to access TimeUtil directly or what is this for?

**Comment by morganick** [comment]
Correct, schedules are serialized with the current time zone. Let's say the user creates the event when their time zone is EST and then later changes their time zone to PST. Now when In interpret those events they will continue to reference their EST time instead of PST which is what the user expects. Since the time zone is serialized into the schedule, I would have to go and update every schedule when the user changes their time zone.

This patch always serializes to UTC and when I deserialize I use the user's time zone.

**Comment by avit** [comment]
I don't think this makes sense to add to the gem, but I'm glad it's working for your use case.

Another option might be to use the standard behaviour, and then adjust the schedule's time zone when reloading it:

```
schedule = IceCube::Schedule.from_yaml(record.schedule)
schedule.start_time = schedule.start_time.in_time_zone(user.time_zone)
```
