### ISSUE TITLE
occurrences_between gives results in unexpected time zone

### ISSUE THREAD

**Issue by supremebeing7** [seejohnrun/ice_cube#285]
I'm creating a schedule with recurrence rules, and when I create one with a weekly recurrence rule, then I run `occurrences_between(begin, end)`, it gives me the results in the time zone of the `begin` value passed in. However, when I create a schedule with a daily recurrence rule, and I run `occurrences_between(begin, end)`, it gives results in UTC.

Relevant code:

    def schedule(starts_at = nil, ends_at = nil)
      starts_at ||= scheduled_from
      ends_at ||= scheduled_to
      if duration > 0
        s = IceCube::Schedule.new(starts_at, end_time: ends_at, duration: duration)
      else
        s = IceCube::Schedule.new(starts_at, end_time: ends_at)
      end
      case repeats
      when 'never'
        s.add_recurrence_time(starts_at)
      when 'daily'
        if repeat_ends == 'never'
          s.add_recurrence_rule IceCube::Rule.daily(repeats_every_n_days)
        else
          s.add_recurrence_rule IceCube::Rule.daily(repeats_every_n_days).until(repeat_ends_on)
        end
      when 'weekly'
        days = repeats_weekly_each_days_of_the_week.map {|d| d.to_sym }
        if repeat_ends == 'never'
          s.add_recurrence_rule IceCube::Rule.weekly(repeats_every_n_weeks).day(*days)
        else
          s.add_recurrence_rule IceCube::Rule.weekly(repeats_every_n_weeks).day(*days).until(repeat_ends_on)
        end
        [...additional config irrelevant to this piece...]
      end
    end

**Comment by avit** [comment]
Sorry for the late reply...

All the occurrences methods on schedules return the time zone of the schedule itself, which comes from `schedule.start_time`. Can you confirm what kind of time you are creating your schedule with?

I will reopen this if it still needs further attention.

**Comment by supremebeing7** [comment]
I'm no longer working on that project so I can't remember any other details. If I find time to investigate this further and still see a problem, I will update.
