### ISSUE TITLE
NameError: uninitialized constant Rule :: how is this suppose to work? 

### ISSUE THREAD

**Issue by brylor** [seejohnrun/ice_cube#286]
Where does Rule come from?

irb(main):023:0> schedule = IceCube::Schedule.new(Time.now) do |s|
irb(main):024:1*  s.add_recurrence_rule(Rule.daily.count(3))
irb(main):025:1>   s.add_exception_time(now + 1.day)
irb(main):026:1> end
NameError: uninitialized constant Rule
	from (irb):24:in `block in irb_binding'
	from /Users/btaylor/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/ice_cube-0.12.1/lib/ice_cube/schedule.rb:24:in `initialize'
	from (irb):23:in `new'
	from (irb):23
	from /Users/btaylor/.rbenv/versions/2.1.4/bin/irb:11:in `<main>'
irb(main):027:0> Rule
NameError: uninitialized constant Rule
	from (irb):27
	from /Users/btaylor/.rbenv/versions/2.1.4/bin/irb:11:in `<main>'

**Comment by seejohnrun** [comment]
you need `IceCube::Rule`

**Comment by TangMonk** [comment]
seems the ReadMe document need to be modify

![image](https://cloud.githubusercontent.com/assets/3498786/8175039/12a55ee6-1417-11e5-9aec-e177aa50caad.png)

**Comment by seejohnrun** [comment]
https://github.com/seejohnrun/ice_cube/pull/290
