### ISSUE TITLE
Side effect changes result of `occurs_on?`

### ISSUE THREAD

**Issue by martinstreicher** [seejohnrun/ice_cube#287]
Here is my debug session:

```
(byebug)  schedule.occurs_on?(time)
false
(byebug) p schedule.start_time
2015-01-01 00:00:00 -0500
2015-01-01 00:00:00 -0500
(byebug)  schedule.occurs_on?(time)
false
(byebug) p schedule.start_time.utc
2015-01-01 05:00:00 UTC
2015-01-01 05:00:00 UTC
(byebug)  schedule.occurs_on?(time)
true
```

Huh? I have no idea why `schedule.start_time.utc` changes the result. Does the call to `.utc` suddenly define what the time zone is?

**Comment by avit** [comment]
Yes that's right... `utc` [mutates the original time]. If you use `getgm` it will [return a new time].

[1]: http://ruby-doc.org/core-2.2.1/Time.html#method-i-utc
[2]: http://ruby-doc.org/core-2.2.1/Time.html#method-i-getgm

**Comment by martinstreicher** [comment]
Thanks. Weird. Should have a `!`
