### ISSUE TITLE
Failing spec on master: 'should not skip times in DST end hour'

### ISSUE THREAD

**Issue by barelyknown** [seejohnrun/ice_cube#291]
I just forked the repo to work on something else and noticed this failing spec. I don't have time now to look into it right now, but wanted to submit the issue so that it is known.

> $ bundle exec rspec spec/examples/hourly_rule_spec.rb:49

>   1) IceCube::HourlyRule should not skip times in DST end hour
     Failure/Error: ]
       expected: `[2013-11-03 00:00:00 -0700, 2013-11-03 00:00:00 -0700, 2013-11-03 01:00:00 -0700, 2013-11-03 02:00:00 -0800]`
            got: `[2013-11-03 00:00:00 -0700, 2013-11-03 01:00:00 -0700, 2013-11-03 01:00:00 -0800, 2013-11-03 02:00:00 -0800]` (using ==)
       Diff:
       
>       @@ -1,5 +1,5 @@
        [2013-11-03 00:00:00 -0700,
       - 2013-11-03 00:00:00 -0700,
         2013-11-03 01:00:00 -0700,
       + 2013-11-03 01:00:00 -0800,
         2013-11-03 02:00:00 -0800]
     # ./spec/examples/hourly_rule_spec.rb:49:in `block (3 levels) in <module:IceCube>'

> 1 example, 1 failure

**Comment by avit** [comment]
I am not seeing this: not sure if it's dependent on your environment, or an old error: what is your TZ?

I will reopen this if it needs further attention.
