### ISSUE TITLE
Business days

### ISSUE THREAD

**Issue by hjansen** [seejohnrun/ice_cube#293]
Hi,

I would need a rule like 

Rule.monthly(1).business_day(1)

That means that this rule applies to the first business day in the month.

A business days is for me when there is no weekend and no bank holiday.
The bank holidays would have to be specified and excluded then on somehow.

Any hints how this could be implemented ?

**Comment by avit** [comment]
You could do:

```
Rule.monthly.day_of_week(:monday => [1])  # first monday of every month
```

There is no handling for holidays, so if you use this you could compare against your own holidays and advance it by 1 day in those cases.

(Sorry for super late reply)
