### ISSUE TITLE
Lower from warn to debug the log IceCube: :#{old_key} is deprecated, please use :#{new_key} at: #{ caller[0] } and similar

### ISSUE THREAD

**Issue by knightq** [seejohnrun/ice_cube#294]
In production is common to have a log level set to `warn`.

Having these logs in production causes:

 - explosion of log size.
 - performance issues.

We don't want to raise the log level to `error` in production neither we are able to quickly sanitize our serialized schedule fileds (*how can we do it quickly, BTW?*).

(*gem version*: **0.12.1**)

**Comment by sgranata82** [comment]
+1

**Comment by avit** [comment]
Fixed in 0.13.3
