### ISSUE TITLE
Weekly rule with no validations

### ISSUE THREAD

**Issue by futbolpal** [seejohnrun/ice_cube#296]
I'm having some trouble wrapping my head around the situation that a weekly rule with no validations has occurrences every week.  How do I discern that from a rule that has a validation on Saturday vs a calendar with no validations, but created on Saturday?

Trying to be more clear, a weekly rule has these occurrences within the next 21 days.
[Mon, 06 Jul 2015 20:33:20 UTC +00:00, Mon, 13 Jul 2015 20:33:20 UTC +00:00, Mon, 20 Jul 2015 20:33:20 UTC +00:00, Mon, 27 Jul 2015 20:33:20 UTC +00:00], even when no validations are added.

Is this a bug?  We have a situation where the user checks black out days, and if they check none, I'm having difficulty understanding what that means on a generic level.  For weeks it might be obvious, but how about hours, months, etc.

Thanks for any/all input!

**Comment by avit** [comment]
Everything is based on the schedule start time. If there are no validations it just repeats from the schedule start, then every week. If you have validations, then it will jump to the first validation, and then repeat weekly from there.
