### ISSUE TITLE
Schedule with no recurrence rules creating an occurrence

### ISSUE THREAD

**Issue by mrodrigues** [seejohnrun/ice_cube#298]
I have an application in which there may or may not be `IceCube::Rule.weekly` rules, and may or may not be `IceCube::SingleOccurrenceRule` rules. When there's no rule, or when there's only `IceCube::SingleOccurrenceRule` rules, the schedule creates an occurrence at the start time passed to its initializer (at `start_time` in `IceCube::Schedule.new(start_time)`).

Is this the expected behaviour or is it a bug? If it's its expected behaviour, how can I avoid the creation of this occurrence?

**Comment by mib32** [comment]
I also noticed that right now, it wasn't before. And it happens not everytime, only at nights (maybe).

Here's the schedule:
`#<IceCube::Schedule:0x007fc0346a8b40 @start_time=2015-07-28 00:33:48 +0300, @all_recurrence_rules=[#<IceCube::SingleOccurrenceRule:0x007fc0346a84b0 @time=Tue, 28 Jul 2015 09:00:00 UTC +00:00, @uses=0>], @all_exception_rules=[]>`

Here is his `all_occurences`
```
2015-07-28 00:33
2015-07-28 09:00
```

It says that it's two, but it should be one. Why?

**Comment by mib32** [comment]
That's right, today, after the night passed, it shows one occurrence again and my tests are passing

Here's the schedule 
```
#<IceCube::Schedule:0x007fcfcbe4c8c8 @start_time=2015-07-28 15:50:19 +0300, @all_recurrence_rules=[#<IceCube::SingleOccurrenceRule:0x007fcfcbe4c238 @time=Tue, 28 Jul 2015 09:00:00 UTC +00:00, @uses=0>], @all_exception_rules=[]>
```

Here is his all_occurences
```
2015-07-28 15:50
```

Which for some reason gives me the current time, not the start time of single rule...

**Comment by mib32** [comment]
+1 :+1:  How can i avoid this?

**Comment by clumsysnake** [comment]
+1 also getting this, and its a problem for my test suite

**Comment by lunks** [comment]
A workaround is to add an exception rule:

```ruby
schedule.add_exception_time(schedule_start)
```

**Comment by willcosgrove** [comment]
I would assume that this is intended behavior.  Your schedule starts at the time of the first occurrence.

**Comment by captainpete** [comment]
Thanks @lunks,
`IceCube::Schedule.new { |s| s.add_exception_time s.start_time }.all_occurrences == []`
works for me.

**Comment by avit** [comment]
Correct, your schedule's start time is always the first occurrence, unless a rule adds validations that advance the time to a different interval.

I can't see that we would change this: what is the use case for an empty schedule? (I'm not ruling that out.) 

You could always make your own:

```
class NullSchedule
  def all_occurrences
    []
  end
end
```
