### ISSUE TITLE
Why does this library skip February?

### ISSUE THREAD

**Issue by ryana** [seejohnrun/ice_cube#299]
This line surprised me:

> Monthly rules will skip months that are too short for the specified day of month (e.g. no occurrences in February for day_of_month(31)).

I was thinking that was the whole point of this library. Doesn't really make any sense to provide a library for calculating recurring dates and then skip entire months, right? I don't see how it's useful with this limitation.

Has there been any discussion around adding this or any patches that will make it work?

**Comment by seejohnrun** [comment]
If you want the last day of the month you can use `-1` - same for any distance from the end of a month - not sure if that helps!  This library is designed around ical - and `day_of_month(31)` doesn't make much sense if it returns a `day=28`!

**Comment by ryana** [comment]
Yeah I thought I could use it for billing. I want to bill monthly based on the day they sign up. If they signup on the 29th - 31st, I need help & was hoping this library could provide it. I guess I'll just say "if you signup on the 29th or 31st then your billing date will be the 28th".

Thx for responding!
