### ISSUE TITLE
Range of time per days

### ISSUE THREAD

**Issue by olivierbuffon** [seejohnrun/ice_cube#300]
Hey guys,
I was wondering if it's possible to limit the recurrence of a rule to a specific range of time.
For example, I would like to generate occurrences every 30 minutes every days between 9:00AM and 6:00PM.
Is there a way to do that ? I tried a couple of times with different rules but without success.
If it's not, I think it could be a very nice add in my opinion.

Thanks.

**Comment by avit** [comment]
This works:

```
IceCube::Rule.hourly.hour_of_day((9..18).to_a)
```

Sorry for the late reply.
