### ISSUE TITLE
#occurrences_between returning inconsistent times when passing through the DST time change

### ISSUE THREAD

**Issue by corroded** [seejohnrun/ice_cube#309]
We have seen that occurrences_between gives us different times given the same recurring event but with different start times. 

Note, this is using Rails 3's `ActiveSupport::TimeWithZone`.

````RUBY
est_string = 'Eastern Time (US & Canada)'

before_dst = Time.new(2015, 10, 27, 5, 15, 0, 0).in_time_zone(est_string)
sched_before_dst = IceCube::Schedule.new(before_dst, duration: 603600)
sched_before_dst.add_recurrence_rule IceCube::Rule.weekly.day(2)
sched_before_dst.occurrences_between(3.weeks.ago, 3.weeks.from_now)

#=> [
# Tue, 27 Oct 2015 01:15:00 EDT -04:00,
# Tue, 03 Nov 2015 01:15:00 EST -05:00,
# Tue, 10 Nov 2015 01:15:00 EST -05:00,
# Tue, 17 Nov 2015 01:15:00 EST -05:00,
# Tue, 24 Nov 2015 01:15:00 EST -05:00
# ]

after_dst = Time.new(2015, 11, 03, 5, 15, 0, 0).in_time_zone(est_string)
sched_after_dst = IceCube::Schedule.new(after_dst, duration: 603600)
sched_after_dst.add_recurrence_rule IceCube::Rule.weekly.day(2)
sched_after_dst.occurrences_between(3.weeks.ago, 3.weeks.from_now)

#=> [
# Tue, 03 Nov 2015 00:15:00 EST -05:00,
# Tue, 10 Nov 2015 00:15:00 EST -05:00,
# Tue, 17 Nov 2015 00:15:00 EST -05:00,
# Tue, 24 Nov 2015 00:15:00 EST -05:00
# ]
````

Note that the only difference is that starting time which was before the DST change(Oct 27) vs after(Nov 3). Both are at 12:15AM and have a duration of 6 days, 23 hours and 40 min. Both have the same recurring schedule (weekly every Tuesday) and as you can see, they have the correct dates but very different hours. To note, in the schedule before the DST change, **Nov 10 becomes 1:15AM EST** but in the schedule after, **Nov 10 stays at 12:15AM EST**. These results can further be proven different by converting them to UTC. Logically, all these dates should be at **05:15AM UTC** but if you convert **Tue, 03 Nov 2015 01:15:00 EST -05:00** to UTC, it advances an hour to **06:15AM UTC**

Is there something we are doing wrong here? Or is it a legitimate bug?

**Comment by jacaetevha** [comment]
This seems like a pretty serious bug. Any thoughts @seejohnrun?

**Comment by jacaetevha** [comment]
I decided to take the example above and convert it to run outside of Rails:
```ruby
require 'ice_cube'
require 'time'
require 'date'

# est_string = 'Eastern Time (US & Canada)'
weeks_ago, weeks_from_now = Date.parse('2015-09-30'), Date.parse('2015-11-30')

puts "BEFORE DST"
# before_dst = Time.new(2015, 10, 27, 5, 15, 0, 0).in_time_zone(est_string)
before_dst = Time.parse('2015-10-27 01:15 EDT')
sched_before_dst = IceCube::Schedule.new(before_dst, duration: 603600)
sched_before_dst.add_recurrence_rule IceCube::Rule.weekly.day(2)
puts sched_before_dst.occurrences_between(weeks_ago, weeks_from_now)

puts "AFTER DST"
# after_dst = Time.new(2015, 11, 03, 5, 15, 0, 0).in_time_zone(est_string)
after_dst = Time.parse('2015-10-27 00:15 EST')
sched_after_dst = IceCube::Schedule.new(after_dst, duration: 603600)
sched_after_dst.add_recurrence_rule IceCube::Rule.weekly.day(2)
puts sched_after_dst.occurrences_between(weeks_ago, weeks_from_now)
```
And it outputs:
```shell
```

**Comment by avit** [comment]
@corroded check the start times you are passing into the schedule:

```
est_string = 'Eastern Time (US & Canada)'

before_dst = Time.new(2015, 10, 27, 5, 15, 0, 0).in_time_zone(est_string)
#=> Tue, 27 Oct 2015 01:15:00 EDT -04:00

after_dst = Time.new(2015, 11, 03, 5, 15, 0, 0).in_time_zone(est_string)
#=> Tue, 03 Nov 2015 00:15:00 EST -05:00
```

Note the hour on these starts out different because of how they were defined. "05:15 +0000" is offset differently from EST depending on the time of year.

@jacaetevha trying the same thing in plain ruby will get you different results. DST only works with your `ENV['TZ']`, where you can use `Time.local`. If you build a time with a manual offset (or different TZ) then it will stay fixed and not change with DST.
