### ISSUE TITLE
Schedule as value object

### ISSUE THREAD

**Issue by sauloperez** [seejohnrun/ice_cube#310]
We're implementing support for models with duration in our rails backend with `IceCube::Schedule` and I wonder whether we could implement the `==`, `eql?` and `hash` methods so that we can determine the equality of two schedules.

So far, we have implemented them in our value object that wraps `IceCube::Schedule`, but it's less than ideal as it forces us to either deal with its internal state or serialize it and compare the resulting strings.

I would be more than happy to implement it myself, but what are your thoughts on this? have you considered it before?

**Comment by avit** [comment]
Yes: I think it's pretty close to being able to do that. There is already `==` for rules, so it would be a question of traversing them all and extending this to the whole schedule. 

You are welcome to submit a pull request, I think it's a great idea.

**Comment by avit** [comment]
Related: #282
