### ISSUE TITLE
i18n update should be a major version bump

### ISSUE THREAD

**Issue by mattnichols** [seejohnrun/ice_cube#312]
The latest version 0.13.1 (introduction of i18n) looks like a nice update. However, it breaks backward compatibility with custom validations. As such probably should have been a major version bump, IMHO. The following code no longer works:

```ruby
        StringBuilder.register_formatter(:year) do |entries|
          "in #{StringBuilder.sentence(entries)}"
        end
```

Now requires invocation of i18n library.

Thanks!

**Comment by avit** [comment]
Agreed, this should have been a `0.next` sorry! :cry: 

I think there was a further change that removes the need for i18n by using an internal implementation if it's not loaded. See here:

https://github.com/seejohnrun/ice_cube/blob/master/lib/ice_cube/i18n.rb

Let me know if that's not working and we can reopen. (I've been absent from this project for a while, so just catching up again.)
