### ISSUE TITLE
Accept Shcedule parameters and translate them to an object

### ISSUE THREAD

**Issue by babaksateli** [seejohnrun/ice_cube#316]
Thanks very much for the GEM. I have been experimenting with it in our new project.

This is more `help needed` rather than an issue!

I am looking forward to see what is the best practice to store the schedule object in the database (ActiveRecord model) as well as retrieve it for the form. 

I did a research and ran into a related GEM called [schedule_attributes](https://github.com/jonjomckay/schedule_attributes) which does pretty much what I am looking for but unfortunately that GEM is out-dated and not compatible with `Rails 4` and `ice_cube 0.13.2` that I am using.

Any advice would be greatly appreciated.

**Comment by daya** [comment]
+1 (schedule_attributes)[https://github.com/jonjomckay/schedule_attributes] is seriously outdated, may be its time to fork and improve on it

**Comment by avit** [comment]
Hi guys, I've been away from this (and related) projects for some time. I'm just getting caught up with it again and I will be happy to make upgrades to both IceCube and ScheduleAttributes. I know it's been a long time, sorry!
