### ISSUE TITLE
Issue with duration of 1.month

### ISSUE THREAD

**Issue by doofpot** [seejohnrun/ice_cube#319]
Hello John,

Setting up a schedule with a fixed duration, everything works fine.

But now, i've a schedule with a duration of 1.month, recurring

schedule.end_time = schedule_start + 1.month
or schedule.duration = 1.month

it's dependent on the starting month for how many day's this event lasts.

For example a monthly recurring event, starting in january (31 day's) gives a good response
starting on february 2015 (28 days), doesn't occur on 30th. march 2016

**Comment by avit** [comment]
Two things are at the core of this issue:

* Rails ActiveSupport defines `1.month == 30.days`, except when you add it to a time
* IceCube schedules can have only one duration for all occurrences

If you try `time + 1.month`, you will see how ActiveSupport does arithmetic: it does some special handling to add the correct number of days based on the current month (30, 31, 28, or 29 days).

However, this is not reliable for exporting to iCal or serializing to hash / YAML format, so we use the strict single duration for the whole schedule.

If your occurrences always run for 1 month, you can work around this by not relying on the duration at all, and just compare the year and month yourself to see if it's "occurring" in the time window.

I'm sorry I can't see a good way to fix this right now, but different durations for occurrences do come up frequently, so we might look into that in the future. It looks like multiple values should be supported as shown in [the spec][rfc5545], but it also says it doesn't support "M" for month durations either...

[rfc5545]: https://tools.ietf.org/html/rfc5545#section-3.3.6
