### ISSUE TITLE
Some help required

### ISSUE THREAD

**Issue by Ganasist** [seejohnrun/ice_cube#330]
I'm having a tough time getting the correct code block for what I need, perhaps one of you experts could help?

I need to create a set of rules that satisfies the following recurring criteria:

- Triggers every 15 minutes between 9a.m. and 7p.m.
- Triggers daily except Sundays
- Triggers for the next 6 months

I know this seems simple but I'm having a tough time layering the rules as needed. Any help would be greatly appreciated.

**Comment by avit** [comment]
Here you go, something like this:

```
end_date = Date.today >> 6
hours = (9..19).to_a
wdays = (1..5).to_a

schedule = IceCube::Schedule.new
every15 = IceCube::Rule.minutely(15)

schedule.add_recurrence_rule(every15.hour_of_day(hours).day(wdays).until(end_date))
```

**Comment by Ganasist** [comment]
Thanks a ton, this was what I needed.
