### ISSUE TITLE
Daylight Savings Time affecting results

### ISSUE THREAD

**Issue by martinstreicher** [seejohnrun/ice_cube#333]
```
ap schedule.to_s
"Daily on the 12th and 18th hours of the day"

(byebug) ap schedule.start_time
Sun, 13 Mar 2016 00:00:00 EST -05:00

(byebug) ap schedule.first
Sun, 13 Mar 2016 12:00:00 EDT -04:00

(byebug) ap schedule.next_occurrence
Sun, 13 Mar 2016 18:00:00 EDT -04:00

(byebug) ap Time.now
2016-03-13 13:00:00 -0400

(byebug) ap Time.current
Sun, 13 Mar 2016 13:00:00 EDT -04:00
```

My start time is in EST. The occurrences are being shown in EDT, perhaps because `Time.current` on 13 March is also in EDT. 

Nonetheless, none of my tests pass because of the mismatch between times due to daylight savings time. I think everything is an hour off.

**Comment by martinstreicher** [comment]
Other rumination:

1/ DST does not stop or end at midnight. It usually occurs at 2 am, so the `EST` for midnight of the 13th is correct. 

2/ However, the events for the schedule occur at 12p and 6p on the 13th, so they occur within daylight savings time. 

How do I set the schedule up so the hours are unaffected by DST? In other words, the schedule would still fire at Noon and 6p of the 13th?

**Comment by avit** [comment]
But, it *does* fire at 12:00 and 18:00 on the 13th based on what you show here:

```
Sun, 13 Mar 2016 12:00:00 EDT -04:00
Sun, 13 Mar 2016 18:00:00 EDT -04:00
```

Maybe your tests are wrong, what are you expecting?

If you want to specify a fixed time offset without daylight savings time then you can specify the offset for your start time: `Time.new(2016, 3, 13, 0, 0, 0, "-05:00")` and your times will always be -05:00 from UTC year-round. This might not match with your expected actual local time though.

Closing this. If we can show this is a real issue, I'm happy to reopen it.
