### ISSUE TITLE
How would you give a name to an event?

### ISSUE THREAD

**Issue by snoblenet** [seejohnrun/ice_cube#339]
How would you recommend we go about giving a name to an event?

I was hoping to do something like:

```
schedule.add_recurrence_rule(
  "soccer practice",
  IceCube::Rule.yearly.day_of_month(13).day(:friday).month_of_year(:october)
)
```

**Comment by CJBrew** [comment]
@snoblenet I am persisting the Schedule in my Database, serialised as a YAML string within my own model. 

I have just realised there's no "name" on Schedule, so shall simply put a name field on my model. That should do the trick.
