### ISSUE TITLE
15 min Time Slots for every day/every week day, help needed?

### ISSUE THREAD

**Issue by tanaylakhani** [seejohnrun/ice_cube#350]
I'm having a tough time getting the correct code block for what I need, perhaps anyone can suggest something? 

I am trying to create user_availabilities that lets user pick what time of the week they are available. I have start_datetime, end_datetime (to set duration/or endtime) and repeat attributes on model. 

Repeat can be - every_day, every_week_day, every_week, every_month

Cruicial part is I need to show availabilities in 15 min time slots. For example: I have availability every week day 9.30am to 5pm then the time slots needs to be 9.30, 9.45, 10.00am ... 4.45pm for all week days

I know this seems simple but I'm having a tough time layering the rules as needed. Any help would be greatly appreciated.

I have tried daily,weekly with specific days and minutely rules.

**Comment by avit** [comment]
Hi, I'm sure it's too late for this answer, but something like this would work:

```
schedule = IceCube::Schedule.new(Time.now, duration: 15*60) do |s|
  s.rrule IceCube::Rule.minutely(15).hour_of_day(9).minute_of_hour(30, 45).second_of_minute(0).day(1,2,3,4,5)
  s.rrule IceCube::Rule.minutely(15).hour_of_day((10..16).to_a).minute_of_hour(0, 15, 30, 45).second_of_minute(0).day(1,2,3,4,5)
end
```

(This approach needs two rules because the first hour doesn't occur at minutes 00 and 15.)
