### ISSUE TITLE
Adjacent schedules conflict when over DST

### ISSUE THREAD

**Issue by elitau** [seejohnrun/ice_cube#351]
I have two weekly recurring schedules that are adjacent. One ends on the end of the day (eg. every Tuesday from 00:00 till 24:00) and the seconds starts at the beginning of the next day(eg. every Wednesday from 00:00 till 24:00). So far, `schedule#conflicts_with?(second_schedule, 6.months.from_now)` works fine and returns `false`.

But when the testing period is over a DST switch the method returns `true`.

```
  it "does not conflict with another bordering schedule over DST" do
    # February 16th in 2010 is a Tuesday
    start_time = Time.utc(2010, 2, 16, 0, 0, 0)
    end_time   = Time.utc(2010, 2, 17, 0, 0, 0)
    schedule1 = IceCube::Schedule.new(start_time, end_time: end_time)
    schedule1.add_recurrence_rule IceCube::Rule.weekly.day(:tuesday)

    schedule2 = IceCube::Schedule.new(start_time, end_time: end_time)
    schedule1.add_recurrence_rule IceCube::Rule.weekly.day(:wednesday)

    expect(schedule1).to_not be_conflicts_with(schedule2, Time.utc(2010, 7, 23, 0, 0, 0))
  end
```

Am I using the start and end time wrongfully? Or is there a bug in IceCube?
I've tried to understand the behaviour in detecting conflicting occurrences but it is really hard to comprehend stuff in there - respect and props for this super helpful gem!

**Comment by avit** [comment]
I'm unable to reproduce this, maybe I'm missing something?

* Your example adds a rule twice to schedule1, I assume both are meant to repeat with 1 rule
* Your example uses UTC time so there is no DST. I tried it with a DST time zone as well

Let us know if you can still reproduce this.
