### ISSUE TITLE
Why is DateTime deprecated?

### ISSUE THREAD

**Issue by Wardrop** [seejohnrun/ice_cube#354]
I've just started using IceCube in a project where I'm already using DateTime, and of course I've been giving IceCube DateTime objects and receiving the warning about DateTime support being deprecated.

I'm just wondering what the motivation behind this is? Why not just continue converting DateTime to Time internally? In my experience, other than speed (which is rarely a concern unless you're writing a library like IceCube), DateTime is typically much nicer to work with.

**Comment by seejohnrun** [comment]
This thread should be able to shed some more light on the motivations: https://github.com/seejohnrun/ice_cube/issues/114

Please comment there if you disagree with this

Thanks!
