### ISSUE TITLE
Multiple dynamic hours in recurring event

### ISSUE THREAD

**Issue by shadowed87** [seejohnrun/ice_cube#359]
I would like to add weekly recurrences, like every monday at 13:00,13.20,14:00,14:40,15:00,15:20
And I am struggling with the add_recurrence_rule, because I have two arrays, one with the days, one with the hours, like this:

weekdays = [:monday,:thursday,:sunday] 
hours = [10:30,11:00,13:20,15:00...]

What I would like to do is to add the rule like so:

schedule = IceCube::Schedule.new(now = Time.now.beginning_of_day) do |s|
 s.add_recurrence_rule(IceCube::Rule.weekly.day(weekdays).hour_of_day(hours))
end

But hours is expecting full hours, like 10:00, 11:00, 12:00 (as integers of course)... How is it possible to add dynamic hours (10:30, 13:20, 15:00) in a recurring weekly event? What approach should I use?

**Comment by shadowed87** [comment]
Ok, this is how I figured it
remember I have
weekdays = ['monday', 'tuesday', 'saturday']
hours = ['10:20', '11:00', '11:30', '13:00', '13:40'....]
`
self.schedule = IceCube::Schedule.new(now = Time.now.beginning_of_week) do |s|
   hours.each do | time |
        time = Time.parse(time)
        opening.hours.each do | time |
          time = Time.parse(time)
          rule = IceCube::Rule.weekly.day(opening.weekdays.map{|s| s.to_sym}).hour_of_day(time.hour).minute_of_hour(time.min)
          s.add_recurrence_rule(rule)
        end
    end
end
`

I loop through the hours, and create a rule with hours and minutes, with the corresponding weekdays, then append it to the scheduler. My question is, is this the right approach?

**Comment by avit** [comment]
Yes, that works. See also #350
