### ISSUE TITLE
Ice Cube ignoring time zone, using UTC instead, issues with daylight saving

### ISSUE THREAD

**Issue by anu-vaid** [seejohnrun/ice_cube#361]
Any help will be appreciated. 

Here's my code
```
# st is Mon, 02 Jan 2017 09:00:00 PST -08:00
ic = IceCube::Schedule.new(st.in_time_zone("Pacific Time (US & Canada)"))
ic.add_recurrence_rule ir
```

However when I call save on the object and print it to console, I see start time in UTC

`#<IceCube::Schedule:0x007fe48ff25140 @start_time=2017-01-02 17:00:00 UTC, ....
`

Why does start time get converted to UTC? Because of this, I am running into issues with occurrences in future and daylight saving being ignored.

**Comment by avit** [comment]
I'm unable to reproduce this. The start time is still in the correct time zone. The test suite also verifies this.

**Comment by wli6** [comment]
We have the same issue,  it happens when your local time zone is "UTC"
