### ISSUE TITLE
IceCube::Schedule.from_ical with invalid inputs throws random errors

### ISSUE THREAD

**Issue by Dorian** [seejohnrun/ice_cube#362]
The rules are user-generated in my use case and I would like to be able to validate them, or catch a single exception (e.g.: `IceCube::InvalidRule`) when they fail.

```
IceCube::Schedule.from_ical('RRULE:')
NoMethodError: undefined method `split' for nil:NilClass
from ~/.rvm/gems/ruby-2.3.3/gems/ice_cube-0.14.0/lib/ice_cube/parsers/ical_parser.rb:29:in `rule_from_ical'
```

I tried fixing #rule_from_ical, but `to_s` and `return nil` throw errors in other parts of the code.

(BTW I tried to create a fuzzer: https://gist.github.com/25c30116746f6606fc65277f494e4294)

**Comment by seejohnrun** [comment]
The problem here is that the first thing the schedule does it split on rules - and you have no rules (ie: the string you have there (I think) is invalid iCalendar format?)

**Comment by Dorian** [comment]
@seejohnrun yes, but shouldn't these errors be categorized as validation errors, e.g. throwing some kind of `IceCube::ValidationError` for instance

**Comment by seejohnrun** [comment]
@Dorian yes, definitely should - I'll get something together
thanks!

**Comment by seejohnrun** [comment]
See: https://github.com/seejohnrun/ice_cube/pull/366

**Comment by avit** [comment]
Closing this issue following those merged changes.

Please reply or reopen if there are any remaining issues causing this error.

**Comment by Dorian** [comment]
(Also #373)
