### ISSUE TITLE
all_occurrences if schedule has :end_time and rules don't have .until or .count

### ISSUE THREAD

**Issue by Extrapolator214** [seejohnrun/ice_cube#367]
Scenario:
- schedule has `@end_time`
- rules don't have `until` or `count`

Currently a call to all_occurrences throws the error:
`All recurrence rules must specify .until or .count to use 'all_occurrences'`

    def all_occurrences
      require_terminating_rules
      enumerate_occurrences(start_time).to_a
    end

Would it be a good idea to rewrite `all_occurrences` (and other methods which call `require_terminating_rules`) to something like the following?

    def all_occurrences
      @end_time || require_terminating_rules
      enumerate_occurrences(start_time, @end_time).to_a
    end

**Comment by avit** [comment]
The `end_time` refers to the end of the first occurrence, in other words it only sets the `duration` of each occurrence, and it would keep repeating forever.

The thing you are looking for is `until`, not `end_time`.
