### ISSUE TITLE
Possible bug in IceCube::Schedule#first()?

### ISSUE THREAD

**Issue by RickCarlino** [seejohnrun/ice_cube#378]
**Intended behavior:**

 * Create a schedule that has less than 100 occurrences (example below, for example, let's say it has 25).
 * Grab the first 100 recurrences of a schedule.
 * I would expect that calling `schedule.first(100).length` would return 25.
 * Instead, I get an array with a length of 100, which goes beyond the schedules time frame.

**Steps to reproduce:**
```
# This creates an array of legnth "100"
# It also adds dates that are beynd the `end_time` of the Schedule.
IceCube::Schedule.new(Date.today, end_time: Date.today + 1.hour) do |sch|
  sch.add_recurrence_rule IceCube::Rule.send(:hourly, 1)
end.first(100).length
```

Is this behavior intended? I originally wanted to use `occurrences_between(start_time, end_time)` but found that the array returned was too large to fit in memory. I thought I could get around it via `.first()` but hit this issue.

 * Is this behavior intended?
 * Are there better ways to do this?

Thanks for the great library!

**Comment by seejohnrun** [comment]
You are looking for `until` which you add to the `rrule`.
It's confusing but is in line with how the iCalendar standard works

Hope this helps!
