### ISSUE TITLE
75 Minute Durations

### ISSUE THREAD

**Issue by jswencki** [seejohnrun/ice_cube#385]
We are having a tough time figuring out the correct rule pattern for durations over an hour. We need to create a schedule that allows an event to be available every hour and X minutes and the next starting at the end of that. 1st occurrence would be 9am, next 10:15am, and so on throughout the day based on the time window. This will repeat each day throughout the week. 

What we are seeing in right now is the second day would start at **10:00am** instead of **9:00am**. This happens on each following day as it appears to be rolling. 

What we need is for it to be the same each day.  Once we hit the next day, it restarts at 9am and is the same available times as the day before. 

Can you provide a sample for this?

Example Problem:
Days: Monday to Friday
Hours allowed: 9a to 5p
Duration: 75 min

**Comment by avit** [comment]
Interesting problem. I can see how "minutely" schedules would cause it to roll over between days and miss the realignment for 09:00 every day...

It may be easier to set up a group of daily rules, each one with its own `hour_of_day` and `minute_of_hour` instead. For 75 minutes, you could do it with a maximum of four rules:

- `daily.hour_of_day((9..17).step(4)).minute_of_hour(0)`
- `daily.hour_of_day((10..17).step(4)).minute_of_hour(15)`
- `daily.hour_of_day((11..17).step(4)).minute_of_hour(30)`
- `daily.hour_of_day((12..17).step(4)).minute_of_hour(45)`
