### ISSUE TITLE
Update gem soon?

### ISSUE THREAD

**Issue by benrugg** [seejohnrun/ice_cube#386]
Hey guys, thank you so much for this library. It's been amazingly helpful to me.

Any chance you're going to update the gem soon? I want to get rid of the Fixnum deprecation warnings in Ruby 2.4 (that were fixed already in commit edd21ea).

**Comment by fwininger** [comment]
:+1:

**Comment by seejohnrun** [comment]
Will get a new release out tonight!

**Comment by benrugg** [comment]
Great! Thank you!

**Comment by seejohnrun** [comment]
https://rubygems.org/gems/ice_cube/versions/0.16.0

**Comment by seejohnrun** [comment]
Thanks!
