### ISSUE TITLE
Readme logical thinking mistake

### ISSUE THREAD

**Issue by Lubmes** [seejohnrun/ice_cube#392]
`schedule.last(2) # [now + 1.day, now + 2.days]`

In the readme should evaluate to `# [now, now + 2.days]`.

If you want to make sense with the schedule made on top, I think.

(What makes things a little unclear, I think, is that this looks the same as `schedule.first(2)`. Maybe better would be to adjust the count from 3 to 4 on the number of days made before the exception above. Then all your examples work.)

**Comment by seejohnrun** [comment]
Thanks @Lubmes - I think the solution you proposed here sounds right to me.
Any interest in submitting a pull request for this change?

**Comment by Lubmes** [comment]
Yes I'll do that. You'll see it coming tomorrow or the day after.

**Comment by seejohnrun** [comment]
Great, thank you!

**Comment by avit** [comment]
Fixed by #393
