### ISSUE TITLE
Missing occurrences on weekly schedules with weekstart mondays

### ISSUE THREAD

**Issue by MGPalmer** [seejohnrun/ice_cube#400]
If you add a schedule like this:
* week start set to monday
* start time on a monday
* weekly
* every day of the week except tuesday

then it will miss the first occurrences...I'll attach a pull request with a spec inn a minute.

**Comment by MGPalmer** [comment]
Ah, update: Yes, this bug only happens with week start monday...unfortunately, this is what our part of the world uses :/

**Comment by MGPalmer** [comment]
Update II: I think I fixed the original problem (the spec I added is green). However, in our production data I found another issue (Biweekly schedules occurring mondays and thursdays, with monday weekstart, seen from a specific date), which I can't fix. I added a spec for this case. All is in the PR.

**Comment by MGPalmer** [comment]
@seejohnrun @avit Sooo, I've been pulling my hair out over this issue - it seems to me like there is a general problem with weekly schedules and starting the week on monday, but I can't grok the code enough to find what's going on. This is a quite bad problem for our service, we keep getting reports about missing occurrences.
Is there any chance of anyone taking a look at this? We'd be willing to offer some sort of bounty for getting timely help :)

**Comment by seejohnrun** [comment]
@MGPalmer I may be able to look tonight or tomorrow morning - email at your convenience. first.last@gmail.com

**Comment by MGPalmer** [comment]
@seejohnrun You've got mail :)

**Comment by seejohnrun** [comment]
@MGPalmer haven't received anything - make sure you put my first and last names in there 😉

**Comment by MGPalmer** [comment]
Strange, I took it from your website...I'll send again from a different account.
