### ISSUE TITLE
Weekly rule when first occurrence is the next day and hour before current hour

### ISSUE THREAD

**Issue by studeba** [seejohnrun/ice_cube#406]
Version 0.16.2 seems to have a problem when creating a weekly schedule when the first occurrence happens to be the next day and the hour_of_day is before the current hour of day.  When this happens, the next_occurrence is pushed out an extra week.  If the hour_of_day is equal to or after the current hour of day, it works fine.

This test works with 0.16.0 but not with 0.16.2
  

    test 'weekly_schedule_flow_next_day_before_hour_test' do

      schedule = IceCube::Schedule.new(Time.utc(2017, 7, 28, 20, 0, 0))

      schedule.add_recurrence_rule IceCube::Rule.weekly(1).day(:saturday).hour_of_day(19)

      result = schedule.next_occurrence(Time.utc(2017, 7, 28, 20, 0, 0))

      assert_equal Time.utc(2017, 7, 29, 19, 0, 0), result, "Should be #{Time.utc(2017, 7, 29, 19, 0, 0)} but got #{result}"

    end

Minitest::Assertion: Should be 2017-07-29 19:00:00 UTC but got 2017-08-05 19:00:00 UTC.

Expected: 2017-07-29 19:00:00 UTC
Actual: 2017-08-05 19:00:00 UTC

**Comment by avit** [comment]
We might have to reset by date (or clear to 00:00:00) when realigning the weekly schedules. I'll try and have a look at this soon.
