### ISSUE TITLE
Bug: improper calculation of "Friday 13th each year"

### ISSUE THREAD

**Issue by garmoshka-mo** [seejohnrun/ice_cube#410]
```
  schedule = IceCube::Schedule.new
  schedule.add_recurrence_rule(
      IceCube::Rule.yearly.day_of_month(13).day(:friday)
  )
  puts schedule.to_s
  puts x = schedule.next_occurrence
  puts x = schedule.next_occurrence(x)
  puts x = schedule.next_occurrence(x)
```

Expected to output: "Yearly on the 13th day of the month on Fridays"
Which should mean "let's have a party 🎉 each year on some Friday 13th" (isn't it?)

But gives only Friday 13th which are in august (why? user didn't specified this rule):
2021-08-13 17:11:32 +0000
2027-08-13 17:11:32 +0000
2032-08-13 17:11:32 +0000

**Comment by seejohnrun** [comment]
I believe you want `monthly` instead of `yearly`:

```
2017-10-13 19:41:06 +0200        
2018-04-13 19:41:06 +0200        
2018-07-13 19:41:06 +0200 
```

**Comment by garmoshka-mo** [comment]
no, once a year on some Friday 13th
`schedule.to_s` says "Yearly on the 13th day of the month on Fridays" and it looks like proper condition but result is improper

**Comment by seejohnrun** [comment]
Sorry, that's not something supported by this library or by iCalendar - the best way is to get all and then filter in Ruby for one per year

**Comment by garmoshka-mo** [comment]
😀
Thank you for suggestion. 
Sometimes temptation to appear right is so strong, that it wins over any common sense and logic even in programming world. Sorry for pointing out, it just looks very funny from a side.

**Comment by seejohnrun** [comment]
Yep - I agree!
