### ISSUE TITLE
Schedule#occurrences doesn't take "end_time" into account?

### ISSUE THREAD

**Issue by mankalas** [seejohnrun/ice_cube#421]
I've got a weekly scheduled event which spans from Today to Tomorrow. Calling `occurrences` on that schedule with a closing time which is in one month, I still get 5 occurrences, although my scheduled event is supposed to end Tomorrow:

```ruby
schedule = IceCube::Schedule.new(Time.now, end_time: Time.now + 1.day) do |s| 
  s.add_recurrence_rule(IceCube::Rule.weekly)
end
schedule.occurrences(Time.now + 1.month).count 
# => 5
```

Have I done something wrong?

**Comment by seejohnrun** [comment]
The `end_time` is for duration, - so it'll still recur the next week at the same time.  You can use `until` as well

**Comment by Bartuz** [comment]
I also found it confusing. @seejohnrun mentioned using `until` and [here](https://github.com/seejohnrun/ice_cube/blame/master/README.md#L106) is the example of it. You apply it to the rule

```
schedule = IceCube::Schedule.new(Time.now) do |s| 
  s.add_recurrence_rule(IceCube::Rule.weekly.until(Time.now + 1.day))
end
```
