### ISSUE TITLE
Wrong object build on Rails 5

### ISSUE THREAD

**Issue by sourabhu-cuelogic** [seejohnrun/ice_cube#429]
I am facing issue in `Rails 5.1.4`, when trying to creat recurring event. In `Rails 4.x.x` it works fine but since I upgraded to `Rails 5`, facing the below issue.

Here is my `params`
> params = {"event":{"data":"title":"gk","event_type":"sync","notify":false,"start_datetime":"2017-11-04 15:30:00 UTC","repeat":true,"schedule":{"occurrence":"daily"},"end_schedule":{"ends":false}},"calendar_options":{"occurrence":"month","startdate":"2017-11-01 00:00:00 UTC"}}
> 2.3.1 :086 > Event.new(params)
>  => #<Event id: nil, title: 'gk', created_by: nil, repeat: false, start_datetime: nil, end_schedule: {}, occurences_completed: 0, data: nil, schedule: #<IceCube::Schedule:0x0000000a8cef60 @start_time=2017-11-03 13:46:21 +0000, @end_time=2017-11-03 14:46:21 +0000, @all_recurrence_rules=[], @all_exception_rules=[]>, event_type: nil, notify: false, notification_schedule: nil, created_at: nil, updated_at: nil> 

When I checked `schedule`, it returns me `IceCube::Schedule` object instead of `Hash`.
> 2.3.1 :087 >event.schedule
 => #<IceCube::Schedule:0x0000000a8cef60 @start_time=2017-11-03 13:46:21 +0000, @end_time=2017-11-03 14:46:21 +0000, @all_recurrence_rules=[], @all_exception_rules=[]>

 Expected:

> 2.3.1 :087 >event.schedule
 => {"occurrence":"daily"}

 What is wrong here, do I need to make some changes to work it.

 Please let me know if you need further information regarding the issue.

**Comment by avit** [comment]
IceCube doesn't do anything to attach itself to your Event rails model. What are you using to integrate it?

**Comment by sourabhu-cuelogic** [comment]
Hi @avit ,

Here is what I am using `ice_cube` with my `ActiveRecord` model.

```
class Event < ApplicationRecord
  include IceCube
  
  serialize :schedule, IceCube::Schedule
end
```

So When object is initializing, I am getting the output as earlier mentioned.

**Comment by saiqulhaq** [comment]
@sourabhu-cuelogic you need to explicitly call #to_hash method, e.g.

```
event.schedule.to_hash
```

![image](https://user-images.githubusercontent.com/1275215/35725578-654b64ec-0834-11e8-98bc-8df23a6f123a.png)
