### ISSUE TITLE
Release 16.3?

### ISSUE THREAD

**Issue by thefliik** [seejohnrun/ice_cube#447]
I love this library! Currently, my `Gemfile` points at
```
gem 'ice_cube', github: 'seejohnrun/ice_cube', ref: 'd0a6b6a'
```
because I make use of the (currently unreleased) `[FEATURE] Added support for parsing RDATE from iCal format`.

I imagine you were originally sitting on the `16.3` release with the assumption that you'd bundle some more features in there before pushing `16.3` out the door. Given that it doesn't look like that's gunna happen though, here's one vote for simply pushing a `16.3` release as is.

Apparently, in order to pull `gem 'ice_cube', github: 'seejohnrun/ice_cube', ref: 'd0a6b6a'` into a container, I also need to install git in the container, which is mildly annoying.

**Comment by seejohnrun** [comment]
all set - thanks @thefliik
