### ISSUE TITLE
A javascript recurrence library

### ISSUE THREAD

**Issue by thefliik** [seejohnrun/ice_cube#457]
When I first started using ice_cube to handle recurring dates, maybe a year+ ago, I wasn't sure how I could also handle recurrence information on the client side. I use rails in api mode to power an Angular application, so the `recurring_select` gem mentioned in the readme wasn't a good choice.

After some hunting, I found [rrulejs](https://github.com/jakubroztocil/rrule), which was pretty nice but, at that time, poorly maintained and buggy. It also didn't support time zones and breaks the ical spec in a few places, and I had to patch ice_cube to work with it. Obviously not ideal (though in the past month one community member has stepped up and fixed most all of these problems).

So I ended up making my own javascript (typescript) recurrence library that supports the ICAL spec and can communicate to/from ice_cube via ICAL strings. You can check it out over at [rSchedule](https://gitlab.com/john.carroll.p/rschedule). It works very well with ice_cube. 

rSchedule has full timezone support (depending on what javascript date library you're using with it), so I've paired it with the ice_cube timezone branch in #455, though that isn't necessary if someone doesn't care about timezone support.

**Anyway, thanks so much for building and maintaining ice_cube for all this time!!!** Having build rSchedule, I know how incredibly time consuming that must have been...

For anyone interested in using ice_cube with a (javascript / typescript) client side app, I'd recommend checking out [rSchedule](https://gitlab.com/john.carroll.p/rschedule), as just sending down a schedule's ICAL string and iterating the dates on the client side is much less data intensive then sending individual dates to the client from the server.

rSchedule supports RRULE, EXRULE, RDATE, and EXDATEs.

#### Example rSchedule usage with ice_cube

**Server side**
```
ical_string = schedule.to_ical
```
**client side**
```
const schedule = Schedule.fromICal(ical_string, StandardDateAdapter)

for (const date of schedule.occurrences()) {
  // do stuff
}

schedule.occursOn({date: new Date()}) // boolean

schedule.occursOn({weekday: 'TU'}) // boolean

schedule.occurrences({start: new Date(), take: 10}).toArray().map(date => date.toISOString())
```

#### ps: I called out ice_cube as inspiration at the end of the project's README :)

**Comment by thefliik** [comment]
@taylorbrooks rSchedule has no UI, it's purely a library for the logic. In this respect it is like ice_cube, except the processing happens on the client side.

In my case, I use it with [`angular-calendar`](https://github.com/mattlewis92/angular-calendar) on the client side (which supplies the UI), but there are other calendar libraries like [`full-calendar`](https://fullcalendar.io/) (plain javascript) that you can use it with (and I'm sure ones for React and Vue).

I haven't made a demo site for it, but it has a [wiki site](https://gitlab.com/john.carroll.p/rschedule/wikis/home) that explains how to use it.

**Comment by seejohnrun** [comment]
Awesome - thanks for the heads up @thefliik this looks great!
