### ISSUE TITLE
i18n v1.2.0 has a breaking change

### ISSUE THREAD

**Issue by lucascaton** [seejohnrun/ice_cube#462]
Hi there.

**i18n v1.2.0** was [released one day ago](https://github.com/svenfuchs/i18n/releases/tag/v1.2.0) and I've noticed one change that affects `ice_cube`: 

Locale's **integer** keys are being converted to **symbols**.

#### Before (`i18n v1.1.1`):

```ruby
require 'bundler/inline'

gemfile do
  gem 'i18n', '1.1.1'
  gem 'ice_cube'
end

puts IceCube::I18n.t('ice_cube.integer.ordinals')
# => {:default=>"th", 1=>"st", 2=>"nd", 3=>"rd", 11=>"th", 12=>"th", 13=>"th"}
```

#### After (`i18n v1.2.0`):

```ruby
require 'bundler/inline'

gemfile do
  gem 'i18n', '1.2.0'
  gem 'ice_cube'
end

puts IceCube::I18n.t('ice_cube.integer.ordinals')
# => {:default=>"th", :"1"=>"st", :"2"=>"nd", :"3"=>"rd", :"11"=>"th", :"12"=>"th", :"13"=>"th"}
```

---

I'm not sure if this is a [i18n](https://github.com/svenfuchs/i18n/) bug or an expected change, but in any case several methods from `lib/ice_cube/builders/string_builder.rb` has stopped working. This is one example:

```ruby
puts IceCube::StringBuilder.nice_number(1)
# [i18n v.1.1.1] => returns `1st`
# [i18n v.1.2.0] => returns `1th`
```

**Comment by CodingAnarchy** [comment]
Well, this explains why I was seeing `Monthly on the 2th Thursday and -1th to last Thursday` all of a sudden.

**Comment by CodingAnarchy** [comment]
It looks like this is the breaking line:
```ruby
 f = IceCube::I18n.t('ice_cube.string.format')[type] ? type : 'default'
```
I believe I can fix this based on the info in svenfuchs/i18n#422.

**Comment by radar** [comment]
Apologies for the issue. Please be aware that this change will be reverted in i18n 1.2.1, which will be released within the next day.

**Comment by radar** [comment]
Could you please test this branch with and without your patch: https://github.com/svenfuchs/i18n/pull/444

I believe it will support both behaviours.

**Comment by CodingAnarchy** [comment]
I have validated that this change to i18n 1.2.1 is still compatible with the patch I have written here.  It is still broken, however, with the old behavior, as the numeric keys are still handled differently.

**Comment by radar** [comment]
Thanks for double checking!

Can you please give me an example of some code that breaks? I will see if I can fix it.

**Comment by radar** [comment]
I have released a new release of i18n (1.3.0) as I said I would do in #444. Please let me know if this is still causing breakages for this gem.

**Comment by CodingAnarchy** [comment]
@radar I don't know that it can be fixed without reverting the symbolizing of Numeric keys, but this is what is breaking:

```ruby
I18n.t('ice_cube.integer.ordinals')
# => {:default=>"th", :"1"=>"st", :"2"=>"nd", :"3"=>"rd", :"11"=>"th", :"12"=>"th", :"13"=>"th"}

IceCube::I18n.t("ice_cube.integer.ordinals")[1] # This is what I have patched to change
# => nil
```

**Comment by radar** [comment]
As of i18n 1.3, the numeric keys are no longer being symbolised. Please confirm that the 1.3 version of i18n works for you.

**Comment by CodingAnarchy** [comment]
I can confirm that i18n 1.3 does work with both `IceCube::I18n.t("ice_cube.integer.ordinals")[1]` and `IceCube::I18n.t("ice_cube.integer.ordinals.1")`

**Comment by radar** [comment]
Great! Thanks for confirming.

**Comment by lucascaton** [comment]
I've updated `i18n` gem to version 1.6.0 (newest version at the moment) and everything is working perfectly again.

Thank you all! 😄
