### ISSUE TITLE
Is it possible to define start time of rules?

### ISSUE THREAD

**Issue by spherop** [seejohnrun/ice_cube#470]
I see clearly that IceCube creates Schedules with a start time that all Rules are based off. I am wondering however if there's any support for adding Rules and Exceptions to Schedules that themselves have distinct start times.

eg something like:

schedule.add_recurrence_rule IceCube::Rule.daily.until(Date.today + 30).startsOn(Date.today + 7)

Or is there any way to achieve this with current functionality?

**Comment by sega** [comment]
Have a look at the README:

> The reason that schedules have durations and not individual rules, is to maintain compatibility with the ical RFC: http://www.kanzaki.com/docs/ical/rrule.html

**Comment by seejohnrun** [comment]
As mentioned above, the RFC at https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html doesn't include any provision for start dates for individual rules.

One way to get the behavior you'd like is separate schedules, although I realize that can be a pain :(
