### ISSUE TITLE
Is still maintained?

### ISSUE THREAD

**Issue by pedrofurtado** [seejohnrun/ice_cube#474]
@seejohnrun @avit 

Is this gem still maintained? The latest stable release and the latest commit are from 2018.

Thanks! :+1: :handshake:

**Comment by pedrofurtado** [comment]
cc @willradi @marciojg

**Comment by fwininger** [comment]
I use this gem and I also would like to know if is this gem still maintained ?

@seejohnrun if you need some help to maintain this gem, I will be very happy to become a maintainer. Let me know.

**Comment by MGPalmer** [comment]
Hello! I could also help out if needed - not currently using this gem anymore, but did so for years and would like to give something back :)

**Comment by jopotts** [comment]
Hi @seejohnrun @avit totally understand if you now have other commitments, but we need to keep the ball rolling with this gem as we're reliant on it! Would it be possible to open it up to additional community members? Thanks!

**Comment by wwahammy** [comment]
I've just stumbled on this gem and it looks great but the maintenance issue is a problem

Perhaps it'd make sense for the folks here to get together and build excitement around a fork. And so we don't have maintainer burnout, it'd be good to develop policies around how people cycle in and out of the maintainer roles.

**Comment by saiqulhaq** [comment]
Let's create a github repo, and for anyone who want to be a maintainer, feel free to comment on this thread

**Comment by fwininger** [comment]
I'm aggree and I will be there to help :)
Who create the organization and the fork ?

**Comment by fwininger** [comment]
May be we can send a email to @seejohnrun to transfert the projet to the organization and have the access to rubygems.

**Comment by jopotts** [comment]
Having recently been involved in a community fork of the [fast_jsonapi](https://github.com/fast-jsonapi/fast_jsonapi) repo due to the maintainers becoming unresponsive, I would MUCH prefer keeping this original repo alive somehow. The main thing is to prevent a gem split. If @avit or @seejohnrun could somehow be involved and either allow additional trusted maintainers or officially hand over to the community then that would be amazing.

**Comment by artofhuman** [comment]
> Let's create a github organization, and for anyone who want to be a maintainer, feel free to comment on this thread

We are using this gem in our app. I'd like to help in supporting

**Comment by fwininger** [comment]
I just send a email to @seejohnrun to request the access of the github repository.

**Comment by seejohnrun** [comment]
I appreciate all of you, and apologize for the delays on changes to this repository. I'm looking through issues & PRs now

**Comment by Frederik-Baetens** [comment]
Was @fwininger still interested in maintaining this? Or what happened there?

**Comment by fwininger** [comment]
I still use this gem in a project so I'm still interested in becoming a maintainer rather than letting this project die. 
@seejohnrun can I have access to this repo ?

**Comment by pedrofurtado** [comment]
@seejohnrun Can you reopen this issue, please?

**Comment by ebendev** [comment]
would love to see a new release cut 👍

**Comment by pacso** [comment]
@seejohnrun - I'd be happy to help maintain this gem. If you can respond by the end of this month allowing myself and @fwininger to become maintainers that would be great. Otherwise I think we'll just need to fork the project.

**Comment by jopotts** [comment]
> @seejohnrun - I'd be happy to help maintain this gem. If you can respond by the end of this month allowing myself and @fwininger to become maintainers that would be great. Otherwise I think we'll just need to fork the project.

I second this. @seejohnrun - please select additional maintainers to help. It would be *much* better than a fork. Thank you as always for all your hard work on this gem over the years. 💎

**Comment by fwininger** [comment]
I send an email to @seejohnrun, I hope I have an answer quickly to be maintainer, otherwise I fork a FireCube project :)

**Comment by pacso** [comment]
Alright ... the fork is dead and I'm now a co-maintainer on this repo helping @seejohnrun keep this thing alive and kicking :)

John has already pushed out a new build (version 0.16.4) which includes everything already in master.
