### ISSUE TITLE
next_occurences ignoring the ending date

### ISSUE THREAD

**Issue by krtschmr** [seejohnrun/ice_cube#475]
even tho we call for 10, it should return only till the end date is reached

![image](https://user-images.githubusercontent.com/13366714/65659087-710c0a80-e054-11e9-9c21-fe54dce5a7ea.png)

**Comment by krtschmr** [comment]
fix would be: https://github.com/krtschmr/ice_cube/commit/6c3b449438b0d099cf7cff7fbdb04fe67f1ae31a#diff-45a3357e6cde86af0c294a51672f4894

**Comment by seejohnrun** [comment]
`end_time` is used to set the duration on the event inside of a given schedule. I think you'll actually want to be using `until` to the set the time horizon for the schedule
