### ISSUE TITLE
Gem::Specification#has_rdoc= is deprecated 

### ISSUE THREAD

**Issue by krtschmr** [seejohnrun/ice_cube#476]
seen on circle ci today

NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /home/circleci/project/vendor/bundle/ruby/2.6.0/bundler/gems/ice_cube-95bf343fc33d/ice_cube.gemspec:20.

**Comment by seejohnrun** [comment]
This has been fixed now, thank you!
