### ISSUE TITLE
German translation of 'Tuesday' is incorrect

### ISSUE THREAD

**Issue by blindMoe** [seejohnrun/ice_cube#481]
It looks like the German translation of Tuesday is incorrect in your locale file.  It is listed as 'Dinstag' but should be 'Dienstag' as it is in the other parts of the same locale file.

Incorrect:
https://github.com/seejohnrun/ice_cube/blob/fb6c657bdc4f87dfda2bf83f15c5f487b78ccabd/config/locales/de.yml#L144

Correct:
https://github.com/seejohnrun/ice_cube/blob/fb6c657bdc4f87dfda2bf83f15c5f487b78ccabd/config/locales/de.yml#L26

I can open up a PR if that helps.  Please let me know.

**Comment by seejohnrun** [comment]
Thank you!
