### ISSUE TITLE
Schedule String incorrect under Ruby 3.0

### ISSUE THREAD

**Issue by ball-hayden** [seejohnrun/ice_cube#492]
Consider the following schedule:

```rb
first_trigger_at = Time.now.utc
schedule = IceCube::Schedule.new(first_trigger_at) do |schedule|
  schedule.add_recurrence_rule(
    IceCube::Rule.weekly.day(
      :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday
    )
  )
end
```

Under Ruby 2.7, this correctly describes itself:

```
schedule.to_s
=> "Weekly on Sundays, Mondays, Tuesdays, Wednesdays, Thursdays, Fridays, and Saturdays"
```

Under Ruby 3.0, `to_s` behaves incorrectly

```
schedule.to_s
=> "%{rest} %{current}"
```

**Comment by lucascaton** [comment]
I'm having a similar issue: by running the same code, it raises an `ArgumentError` exception:

```ruby
# ...
schedule.to_s
# ArgumentError: wrong number of arguments (given 2, expected 0..1)
# from ~/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/i18n-1.8.7/lib/i18n.rb:195:in `translate'
```

I'm using `ice_cube` version `0.16.3`.

**Comment by jeffblake** [comment]
Ruby 3 will cause the argument error. As a temp workaround, I added an initializer with this:

```
# Temp fix due to ruby 3 argument error
module IceCube
  module I18n

    def self.backend
      NullI18n
    end
  end
end
```

Naturally this loses i18n, but in my case it's not a big deal.

**Comment by fwininger** [comment]
This issue can be solved by using the current master branch, with this commit : https://github.com/seejohnrun/ice_cube/commit/66f1d797092734563bfabd2132c024c7d087f683

The delegate usage introduce a rails dependency but remove this issue.

**Comment by ball-hayden** [comment]
@seejohnrun any chance you might be able to cut a release that includes 66f1d79 so we can have Ruby 3 support?

**Comment by rikkipitt** [comment]
I'd be interested in seeing 66f1d79  in a new release too if you get a chance. I'll use the gem via Git for now.

Cheers folks!

**Comment by pacso** [comment]
@seejohnrun - Another request for an updated release please! We just upgraded to Ruby 3, and now have to load this gem from the master branch. 🙏🏻

**Comment by lucascaton** [comment]
Hi @seejohnrun - do you have any news on this? Is there anything we can do to help?

**Comment by pacso** [comment]
No releases for ~2 years ... should we consider this project dead and fork it?

**Comment by fwininger** [comment]
https://github.com/seejohnrun/ice_cube/issues/474 @pacso

**Comment by Frederik-Baetens** [comment]
Hmm, but the last comments there are from about a year ago now. I very much appreciate the work seejohnrun has been doing, but I think it's a bit of a shame if people are willing to take up maintainership, but aren't able to do so.

**Comment by seejohnrun** [comment]
Happy to open the door to other maintainers, if you're interested in helping maintain this project I appreciate you - let's chat over on #474

**Comment by vdegove** [comment]
Yup, would be greatly appreciated if the version on RubyGems was bumped based on current master. Current master works great on Ruby 3.0. On #474 there seems to be someone, @fwininger, ready to take care of gem repo and update RubyGems.

**Comment by fwininger** [comment]
@vdegove of course, if @seejohnrun have time to give me the access.

**Comment by sallesma** [comment]
Awesome, thanks!

We just ejected from ice_cube 1 week ago because it was unmaintained. If we needed to use it again, we would definitely have a look at your fork!

**Comment by pacso** [comment]
Alright ... the fork is dead and I'm now a co-maintainer on this repo helping @seejohnrun keep this thing alive and kicking :) 

John has already pushed out a new build ([version 0.16.4](https://rubygems.org/gems/ice_cube/versions/0.16.4)) which includes everything already in `master`. Consequently this issue is resolved on the current release of the gem.
