### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by pjb3** [seejohnrun/ice_cube#6]
This will produce an infinite loop, at least it does for me on Ruby 1.8.6

```
require "rubygems"
require "ice_cube"
require "time"

schedule = IceCube::Schedule.new(Time.parse("2010-08-30"))
schedule.add_recurrence_rule IceCube::Rule.monthly(6)
puts schedule.occurrences_between(Time.parse("2010-07-01"), Time.parse("2010-09-01"))
```

**Comment by lacostenycoder** [comment]
Hey I was looking at the specs to get more insight into the workings [and found this spec ](https://github.com/seejohnrun/ice_cube/blob/master/spec/examples/ice_cube_spec.rb#L493)which refs this issue has no expectation
`¯\_(ツ)_/¯`
