### ISSUE TITLE
Localization for rule descriptions

### ISSUE THREAD

**Issue by mruokojo** [seejohnrun/ice_cube#68]
Hi!

I could not find any specs about how to localize rule string result. I need to localize for example rule string "Weekly, on tuesdays".

**Comment by TangMonk** [comment]
+1

**Comment by Frank004** [comment]
+1 for this!

**Comment by Frank004** [comment]
its there a way to add it manualy for one language ?? thank you great gem

**Comment by joelmeyerhamme** [comment]
You could copy a locale file and make a pull request. What language would that be? There reason I haven't been working on this, is that I lack the understanding of how to generalise the locale format so that it would work with as many different languages as possible.

**Comment by dgilperez** [comment]
@Frank004 it looks like this fork is working. You can PR them with your language file.

https://github.com/gocardless/ice_cube

**Comment by Frank004** [comment]
@joelmeyerhamme  and @dgilperez  Hi I got it working using this one gem 'ice_cube'  , :git => 'git://github.com/dgilperez/ice_cube.git'.  Thanks for this great gem. Save us days and days of code

**Comment by avit** [comment]
This was done in #311. Thanks everyone!
