### ISSUE TITLE
next_occurrences uses current milliseconds

### ISSUE THREAD

**Issue by bitboxer** [seejohnrun/ice_cube#84]
It seems like next_occurrences is using the current milliseconds and creates different Time objects each time the method is called due to that.

**Comment by clumsysnake** [comment]
@seejohnrun unfortunately this means that if you pass in a start time as normal time object, occurrences will still have milliseconds. minor issue but recording here for posterity:

``` ruby
 IceCube::Schedule.new(Time.now).tap {|s| s.rrule IceCube::Rule.weekly.day(:monday) }.next_occurrence.start_time.usec
526086
```
